=== TheITFirefly/centibudget-web/src/lib/schemas/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "CentiBudget",
  "description": "Everything needed for CentiBudget, a personal finance system",
  "type": "object",
  "properties": {
    "Schema Version": {
      "type": "string",
      "pattern": "^([0-9]+\\.){2}([0-9]+)$"
    },
    "Last Modification Date": {
      "type": "string",
      "format": "date",
      "examples": ["2021-12-31", "2022-01-01"]
    },
    "Funding Sources": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "Name": {
            "type": "string",
            "minLength": 1
          },
          "Funding Type": {
            "enum": [
              "Salary",
              "Hourly"
            ]
          },
          "Rate": {
            "type": "number",
            "minimum": 0
          },
          "Pay Timing": {
            "type": "object",
            "properties": {
              "Start Date": {
                "anyOf": [
                  {
                    "type": "string",
                    "format": "date",
                    "examples": ["2021-12-31", "2022-01-01"]
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "First Pay Date": {
                "type": "string",
                "format": "date",
                "examples": ["2021-12-31", "2022-01-01"]
              },
              "Period": {
                "enum": [
                  "Weekly",
                  "Biweekly",
                  "Monthly",
                  "Yearly",
                  "One-time"
                ]
              },
              "End Date": {
                "anyOf": [
                  {
                    "type": "string",
                    "format": "date",
                    "examples": ["2021-12-31", "2022-01-01"]
                  },
                  {
                    "type": "null"
                  }
                ]
              }
            }
          },
          "Hours Per Pay Period": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "required": ["Name", "Funding Type", "Rate", "Pay Timing", "Hours Per Pay Period"],
        "additionalProperties": false
      }
    },
    "Accounts": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "Name": {
            "type": "string",
            "minLength": 1
          },
          "Balance": {
            "type": "number"
          },
          "Transactions": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "Name": {
                  "anyOf": [
                    {
                      "type": "string",
                      "minLength": 1
                    },
                    {
                      "type": "null"
                    }
                  ]
                },
                "Amount": {
                  "type": "number"
                },
                "Date": {
                  "type": "string",
                  "format": "date",
                  "examples": ["2021-12-31", "2022-01-01"]
                }
              },
              "required": ["Name", "Amount", "Date"],
              "additionalProperties": false
            }
          }
        },
        "required": ["Name", "Balance", "Transactions"],
        "additionalProperties": false
      }
    },
    "Allocations": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "Name": {
            "type": "string",
            "minLength": 1
          },
          "Type": {
            "enum": [
              "Fixed",
              "Percentage",
              "Subscription"
            ]
          },
          "Period": {
            "enum": [
              "Weekly",
              "Biweekly",
              "Monthly",
              "Yearly",
              "One-time",
              "Constant"
            ]
          },
          "Last Paid": {
            "anyOf": [
              {
                "type": "string",
                "format": "date",
                "examples": ["2021-12-31", "2022-01-01"]
              },
              {
                "type": "null"
              }
            ]

          },
          "Amount": {
            "type":"number"
          },
          "Account": {
            "type": "string"
          }
        },
        "required": ["Name", "Type", "Period", "Last Paid", "Amount", "Account"],
        "additionalProperties": false
      }
    }
  },
  "required": ["Schema Version", "Last Modification Date", "Funding Sources", "Allocations", "Accounts"],
  "additionalProperties": false
}

=== TheITFirefly/centibudget-web/src/lib/schemas/example-output.json
{
  "Schema Version": "2.0.1",
  "Last Modification Date": "2025-04-21",
  "Funding Sources": [
    {
      "Name": "full-time source",
      "Funding Type": "Hourly",
      "Rate": 17.50,
      "Pay Timing": {
        "Start Date": null,
        "First Pay Date": "2025-05-23",
        "Period":"Biweekly",
        "End Date": null
      },
      "Hours Per Pay Period": 40
    },
    {
      "Name": "part-time source",
      "Funding Type": "Hourly",
      "Rate": 21,
      "Pay Timing": {
        "Start Date": null,
        "First Pay Date": "2025-05-23",
        "Period": "Biweekly",
        "End Date": null
      },
      "Hours Per Pay Period": 20
    },
    {
      "Name": "student source",
      "Funding Type": "Hourly",
      "Rate": 22.00,
      "Pay Timing": {
        "Start Date": "2025-05-09",
        "First Pay Date":"2025-05-23",
        "Period":"Biweekly",
        "End Date": "2025-08-29"
      },
      "Hours Per Pay Period": 40
    },
    {
      "Name": "student source",
      "Funding Type": "Hourly",
      "Rate": 22.00,
      "Pay Timing": {
        "Start Date": "2025-08-29",
        "First Pay Date":"2025-08-29",
        "Period": "Biweekly",
        "End Date": null
      },
      "Hours Per Pay Period": 20
    },
    {
      "Name": "salary source",
      "Funding Type": "Salary",
      "Rate": 65000.00,
      "Pay Timing": {
        "Start Date": null,
        "Period": "Monthly"
      },
      "Hours Per Pay Period": null
    }
  ],
  "Accounts": [
    {
      "Name": "Emergency Fund",
      "Balance": 6000.00,
      "Transactions": [
        {
          "Name": null,
          "Amount": -20.00,
          "Date": "2025-05-28"
        }
      ]
    },
    {
      "Name": "Tithing",
      "Balance": 6000.00,
      "Transactions": []
    },
    {
      "Name": "Entertainment",
      "Balance": 45.43,
      "Transactions": []
    },
    {
      "Name": "Dance",
      "Balance": 124.50,
      "Transactions": [
        {
          "Name": "Dance shoes",
          "Amount": -125.00,
          "Date":"2025-05-28"
        },
        {
          "Name": "Deposit",
          "Amount": 125.00,
          "Date":"2025-05-27"
        }
      ]
    },
    {
      "Name": "Gifts",
      "Balance": 359.00,
      "Transactions": []
    }
    
  ],
  "Allocations": [
    {
      "Name": "Tithing",
      "Type": "Percentage",
      "Period": "Constant",
      "Last Paid": null,
      "Amount": 10.00,
      "Account": "Tithing"
    },
    {
      "Name": "Emergency Fund",
      "Type": "Fixed",
      "Period": "One-time",
      "Last Paid": null,
      "Amount": 12000.00,
      "Account": "Emergency Fund"
    },
    {
      "Name": "Spotify",
      "Type": "Subscription",
      "Period": "Monthly",
      "Last Paid": "2021-12-31",
      "Amount": 12000.00,
      "Account": "Entertainment"
    },
    {
      "Name": "Gifts",
      "Type": "Percentage",
      "Period": "One-time",
      "Last Paid": null,
      "Amount": 15.00,
      "Account": "Gifts"
    },
    {
      "Name": "Dance shoes",
      "Type": "Fixed",
      "Period": "One-time",
      "Last Paid": null,
      "Amount": 350.00,
      "Account": "Dance"
    },
    {
      "Name": "Lessons",
      "Type": "Subscription",
      "Period": "Weekly",
      "Last Paid": "2021-12-31",
      "Amount": 80.00,
      "Account": "Dance"
    }
  ]
}
